// Данные товаров — автоматически сгенерировано админкой
// Последнее обновление: 2024-01-01 00:00:00

const productsData = [
    {
        id: 1,
        name: "Лавандовое поле",
        price: 2900,
        images: ["images/1.jpeg", "images/2.jpeg", "images/3.jpeg"],
        category: "Букеты",
        packaging: "kraft",
        packagingName: "Крафт упаковка",
        packagingIcon: "📜",
        description: "Ароматная лаванда в сочетании с полевыми травами создаёт атмосферу прованса.",
        sizes: "Высота: 50 см, Ширина: 40 см",
        heightCm: 50,
        widthCm: 40,
        composition: "Лаванда, статица, гипсофила, хлопок",
        care: "Беречь от прямых солнечных лучей, не поливать"
    },
    {
        id: 2,
        name: "Осенний вальс",
        price: 3500,
        images: ["images/13.png", "images/5.jpeg", "images/6.jpeg"],
        category: "Композиции",
        packaging: "vase",
        packagingName: "В кашпо",
        packagingIcon: "🏺",
        description: "Тёплые оттенки осени в изящной композиции.",
        sizes: "Высота: 45 см, Ширина: 35 см",
        heightCm: 15,
        widthCm: 15,
        composition: "Гортензия, физалис, лимониум",
        care: "Беречь от влаги, размещать вдали от отопительных приборов"
    },
    {
        id: 3,
        name: "Эко-минимализм",
        price: 2700,
        images: ["images/7.jpeg", "images/8.jpeg", "images/9.jpeg"],
        category: "Панно",
        packaging: "none",
        packagingName: "Без упаковки",
        packagingIcon: "✨",
        description: "Лаконичная композиция в эко-стиле.",
        sizes: "Высота: 40 см, Ширина: 30 см",
        heightCm: 40,
        widthCm: 30,
        composition: "Пшеница, пампасная трава, эвкалипт",
        care: "Сухое место, защищённое от прямых солнечных лучей"
    },
    {
        id: 4,
        name: "Небесная лазурь",
        price: 4200,
        images: ["images/10.jpeg", "images/11.jpeg", "images/12.jpeg"],
        category: "Букеты",
        packaging: "vase",
        packagingName: "В кашпо",
        packagingIcon: "🏺",
        description: "Нежные голубые и синие оттенки сухоцветов.",
        sizes: "Высота: 55 см, Ширина: 45 см",
        heightCm: 55,
        widthCm: 45,
        composition: "Бруния, эрмингия, эвкалипт, статица",
        care: "Оберегать от детей и домашних животных"
    },
    {
        id: 5,
        name: "Деревенский шарм",
        price: 3100,
        images: ["images/13.png", "images/14.jpeg", "images/15.jpeg"],
        category: "Композиции",
        packaging: "kraft",
        packagingName: "Крафт упаковка",
        packagingIcon: "📜",
        description: "Рустикальный букет с нотками прованса.",
        sizes: "Высота: 45 см, Ширина: 35 см",
        heightCm: 280,
        widthCm: 250,
        composition: "Лаванда, хлопок, пшеница, сухоцветы",
        care: "Не требует особого ухода, сохраняет вид до 3 лет"
    },
    {
        id: 6,
        name: "Зимняя сказка",
        price: 4800,
        images: ["images/16.jpeg", "images/17.jpeg", "images/1.jpeg"],
        category: "Букеты",
        packaging: "vase",
        packagingName: "В кашпо",
        packagingIcon: "🏺",
        description: "Белоснежные и серебристые сухоцветы.",
        sizes: "Высота: 50 см, Ширина: 40 см",
        heightCm: 50,
        widthCm: 40,
        composition: "Лунулария, хлопок, гипсофила, бессмертник",
        care: "Размещать в сухом проветриваемом месте"
    },
    {
        id: 7,
        name: "Ботанический сад",
        price: 3900,
        images: ["images/2.jpeg", "images/3.jpeg", "images/4.jpeg"],
        category: "Композиции",
        packaging: "none",
        packagingName: "Без упаковки",
        packagingIcon: "✨",
        description: "Микс из разнообразных сухоцветов.",
        sizes: "Высота: 60 см, Ширина: 50 см",
        heightCm: 60,
        widthCm: 50,
        composition: "Разнотравье, декоративные злаки",
        care: "Избегать попадания прямых солнечных лучей"
    },
    {
        id: 8,
        name: "Розовый закат",
        price: 3400,
        images: ["images/5.jpeg", "images/6.jpeg", "images/7.jpeg"],
        category: "Букеты",
        packaging: "kraft",
        packagingName: "Крафт упаковка",
        packagingIcon: "📜",
        description: "Нежные розовые и пудровые оттенки.",
        sizes: "Высота: 45 см, Ширина: 35 см",
        heightCm: 45,
        widthCm: 35,
        composition: "Гортензия, розовые сухоцветы, статица",
        care: "Хранить в сухом месте"
    },
    {
        id: 9,
        name: "Средиземноморье",
        price: 4500,
        images: ["images/8.jpeg", "images/9.jpeg", "images/10.jpeg"],
        category: "Композиции",
        packaging: "vase",
        packagingName: "В кашпо",
        packagingIcon: "🏺",
        description: "Средиземноморские травы и цветы.",
        sizes: "Высота: 55 см, Ширина: 45 см",
        heightCm: 55,
        widthCm: 45,
        composition: "Лаванда, розмарин, оливковые ветви",
        care: "Периодически проветривать помещение"
    },
    {
        id: 10,
        name: "Прованс",
        price: 3800,
        images: ["images/11.jpeg", "images/12.jpeg", "images/13.png"],
        category: "Букеты",
        packaging: "kraft",
        packagingName: "Крафт упаковка",
        packagingIcon: "📜",
        description: "Французский шарм в каждой детали.",
        sizes: "Высота: 50 см, Ширина: 40 см",
        heightCm: 50,
        widthCm: 40,
        composition: "Лаванда, розмарин, тимьян",
        care: "Беречь от влаги, хранить в сухом месте"
    },
    {
        id: 11,
        name: "Морской бриз",
        price: 4100,
        images: ["images/14.jpeg", "images/15.jpeg", "images/16.jpeg"],
        category: "Композиции",
        packaging: "vase",
        packagingName: "В кашпо",
        packagingIcon: "🏺",
        description: "Свежие оттенки голубого и белого.",
        sizes: "Высота: 50 см, Ширина: 40 см",
        heightCm: 50,
        widthCm: 40,
        composition: "Эрмингия, бруния, морская статица",
        care: "Не требует особого ухода, беречь от прямых лучей"
    },
    {
        id: 12,
        name: "Золотая осень",
        price: 3600,
        images: ["images/17.jpeg", "images/1.jpeg", "images/2.jpeg"],
        category: "Букеты",
        packaging: "kraft",
        packagingName: "Крафт упаковка",
        packagingIcon: "📜",
        description: "Яркие золотистые и оранжевые оттенки.",
        sizes: "Высота: 45 см, Ширина: 35 см",
        heightCm: 45,
        widthCm: 35,
        composition: "Физалис, лимониум, декоративные ветки",
        care: "Избегать попадания прямых солнечных лучей"
    },
    {
        id: 13,
        name: "Белоснежное утро",
        price: 5200,
        images: ["images/3.jpeg", "images/4.jpeg", "images/5.jpeg"],
        category: "Композиции",
        packaging: "vase",
        packagingName: "В кашпо",
        packagingIcon: "🏺",
        description: "Элегантная белая композиция.",
        sizes: "Высота: 55 см, Ширина: 45 см",
        heightCm: 55,
        widthCm: 45,
        composition: "Белый хлопок, гипсофила, лунулария",
        care: "Хранить в сухом проветриваемом месте"
    },
    {
        id: 14,
        name: "Вдохновение",
        price: 3300,
        images: ["images/6.jpeg", "images/7.jpeg", "images/8.jpeg"],
        category: "Панно",
        packaging: "none",
        packagingName: "Без упаковки",
        packagingIcon: "✨",
        description: "Авторская композиция для интерьера.",
        sizes: "Высота: 40 см, Ширина: 30 см",
        heightCm: 40,
        widthCm: 30,
        composition: "Сухоцветы, злаки, декоративные элементы",
        care: "Беречь от механических повреждений"
    },
    {
        id: 15,
        name: "Лесная сказка",
        price: 4000,
        images: ["images/9.jpeg", "images/10.jpeg", "images/11.jpeg"],
        category: "Композиции",
        packaging: "kraft",
        packagingName: "Крафт упаковка",
        packagingIcon: "📜",
        description: "Сочетание лесных мхов, шишек и сухоцветов.",
        sizes: "Высота: 50 см, Ширина: 40 см",
        heightCm: 50,
        widthCm: 40,
        composition: "Мох, шишки, эвкалипт, ягоды",
        care: "Не поливать, беречь от влаги"
    },
    {
        id: 16,
        name: "Кофейное настроение",
        price: 2900,
        images: ["images/12.jpeg", "images/13.png", "images/14.jpeg"],
        category: "Букеты",
        packaging: "kraft",
        packagingName: "Крафт упаковка",
        packagingIcon: "📜",
        description: "Тёплые кофейные и шоколадные оттенки.",
        sizes: "Высота: 40 см, Ширина: 30 см",
        heightCm: 40,
        widthCm: 30,
        composition: "Пшеница, физалис, пампасная трава",
        care: "Беречь от прямых солнечных лучей"
    },
    {
        id: 17,
        name: "Сиреневый туман",
        price: 4600,
        images: ["images/15.jpeg", "images/16.jpeg", "images/17.jpeg"],
        category: "Композиции",
        packaging: "vase",
        packagingName: "В кашпо",
        packagingIcon: "🏺",
        description: "Нежные сиреневые оттенки.",
        sizes: "Высота: 55 см, Ширина: 45 см",
        heightCm: 55,
        widthCm: 45,
        composition: "Лаванда, сирень, статица",
        care: "Размещать вдали от детей и животных"
    },
    {
        id: 18,
        name: "Дикая природа",
        price: 3700,
        images: ["images/1.jpeg", "images/2.jpeg", "images/3.jpeg"],
        category: "Букеты",
        packaging: "none",
        packagingName: "Без упаковки",
        packagingIcon: "✨",
        description: "Естественная красота диких трав и цветов.",
        sizes: "Высота: 50 см, Ширина: 40 см",
        heightCm: 50,
        widthCm: 40,
        composition: "Дикие травы, злаки, полевые цветы",
        care: "Не требует особого ухода"
    },
    {
        id: 19,
        name: "Ягодное ассорти",
        price: 4400,
        images: ["images/4.jpeg", "images/5.jpeg", "images/6.jpeg"],
        category: "Композиции",
        packaging: "vase",
        packagingName: "В кашпо",
        packagingIcon: "🏺",
        description: "Сочетание сухоцветов с декоративными ягодами.",
        sizes: "Высота: 55 см, Ширина: 45 см",
        heightCm: 55,
        widthCm: 45,
        composition: "Ягоды, сухоцветы, декоративные ветки",
        care: "Беречь от механических воздействий"
    },
    {
        id: 20,
        name: "Гармония",
        price: 5000,
        images: ["images/7.jpeg", "images/8.jpeg", "images/9.jpeg"],
        category: "Панно",
        packaging: "none",
        packagingName: "Без упаковки",
        packagingIcon: "✨",
        description: "Большая композиция для просторных помещений.",
        sizes: "Высота: 65 см, Ширина: 55 см",
        heightCm: 65,
        widthCm: 55,
        composition: "Смешанные сухоцветы, злаки",
        care: "Размещать в хорошо проветриваемом месте"
    }
];

const masterClassesData = [
    {
        id: 1,
        name: "Живая картина из мха",
        price: 2500,
        duration: "2 часа",
        image: "images/2.jpeg",
        description: "Создайте вертикальное панно из стабилизированного мха",
        icon: "🌿"
    },
    {
        id: 2,
        name: "Авторская композиция",
        price: 2800,
        duration: "2.5 часа",
        image: "images/4.jpeg",
        description: "Соберите букет из сухоцветов по своему вкусу",
        icon: "💐"
    },
    {
        id: 3,
        name: "Создание керамических цветов",
        price: 2200,
        duration: "2 часа",
        image: "images/10.jpeg",
        description: "Слепите цветок из глины за один вечер. Забираете готовое изделие после обжига. Все материалы даём. Для начинающих.",
        icon: "🏺"
    }
];